version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2

  backend1:
    build: 
      context: ./backend
    environment:
      - PORT=3001
    ports:
      - "3001:3000"

  backend2:
    build: 
      context: ./backend
    environment:
      - PORT=3002
    ports:
      - "3002:3000"