services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    build: 
      context: ./backend
    environment:
      - PORT=3001
    ports:
      - "3001:3000"

  backend2:
    build: 
      context: ./backend
    environment:
      - PORT=3002
    ports:
      - "3002:3000"

  backend3:
    build: 
      context: ./backend
    environment:
      - PORT=3003
    ports:
      - "3003:3000"

  tester:
    build:
      context: ./tester
    depends_on:
      - nginx
      - backend1
      - backend2
      - backend3
    volumes:
      - ./tester/reports:/app/reports  